//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputerParts.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Monitor
    {
        public int MonitorId { get; set; }
        public string Image { get; set; }
        public string Name { get; set; }
        public string Information { get; set; }
        public Nullable<decimal> Price { get; set; }
    }
}
