//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputerParts.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Part
    {
        public int Id { get; set; }
        public Nullable<int> CaseId { get; set; }
        public Nullable<int> MotherboardId { get; set; }
        public Nullable<int> CPUId { get; set; }
        public Nullable<int> RAMId { get; set; }
        public Nullable<int> SSDId { get; set; }
        public Nullable<int> HDDId { get; set; }
        public Nullable<int> GPUId { get; set; }
        public Nullable<int> OpticalDriveId { get; set; }
        public Nullable<int> MonitorId { get; set; }
        public Nullable<int> PeripheralId { get; set; }
    }
}
