//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputerParts.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PCPartsEntities1 : DbContext
    {
        public PCPartsEntities1()
            : base("name=PCPartsEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Case> Cases { get; set; }
        public virtual DbSet<CPU> CPUs { get; set; }
        public virtual DbSet<GPU> GPUs { get; set; }
        public virtual DbSet<HDD> HDDs { get; set; }
        public virtual DbSet<Monitor> Monitors { get; set; }
        public virtual DbSet<Motherboard> Motherboards { get; set; }
        public virtual DbSet<OpticalDrive> OpticalDrives { get; set; }
        public virtual DbSet<Part> Parts { get; set; }
        public virtual DbSet<Peripheral> Peripherals { get; set; }
        public virtual DbSet<RAM> RAMs { get; set; }
        public virtual DbSet<SSD> SSDs { get; set; }
        public virtual DbSet<CartItem> CartItems { get; set; }
    }
}
